"""Initial migration

Revision ID: 07f0120eb5a2
Revises: 
Create Date: 2025-04-01 02:33:41.787205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f0120eb5a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pack_size_label',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('uses',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               nullable=False)
        batch_op.alter_column('side_effects',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               nullable=False)
        batch_op.alter_column('composition',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               nullable=False)
        batch_op.alter_column('manufacturer',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('manufacturer',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('composition',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('side_effects',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('uses',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('pack_size_label',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('stock',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
