"""Initial migration

Revision ID: bd8655f74398
Revises: 
Create Date: 2024-12-20 16:17:48.120019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd8655f74398'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('pack_size_label',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('uses',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('side_effects',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('composition',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('composition',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('side_effects',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('uses',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('pack_size_label',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
